### ISSUE TITLE
new release for jasmine-npm?

### ISSUE THREAD

**Issue by cnishina** [jasmine/jasmine-npm#102]
Could we get a new hot fix release for jasmine-npm? Protractor is holding back on upgrading to 2.5.x due to jasmineNodeOpts print not working. See https://github.com/angular/protractor/issues/3609. We have since downgraded to 2.4.x. This is the PR we fixed on https://github.com/jasmine/jasmine-npm/pull/98. Thanks!

**Comment by cnishina** [comment]
@slackersoft is there a timeline on 2.5.3?

**Comment by slackersoft** [comment]
Released: https://github.com/jasmine/jasmine-npm/releases/tag/v2.5.3

**Comment by cnishina** [comment]
@slackersoft Thanks!
