### ISSUE TITLE
async support not working when using jasmine.execute();

### ISSUE THREAD

**Issue by kaiwah** [jasmine/jasmine-npm#104]
So I encountered a strange result when trying to test some jasmine specs. I have a spec runner called `spec/init.js` that just instantiates a jasmine object and sets the reporter. And I have a spec file with 2 basics tests, 1 being a quick truthy-falsey test, and other being a async spec that was pretty much copy/pasted from the jasmine.js docs. 

The strange thing is when I run the spec runner, `jasmine spec/init.js`, I get the following:
```
Started
.Started


No specs found
Finished in 0.002 seconds
```

but if I execute the spec directly with `jasmine spec/test-actions.spec.js`, I get the correct result:
```
Started
..


2 specs, 0 failures
Finished in 2.514 seconds
```
Removing the async spec from the file, it works fine. And after a bit of tinkering, it seems the `done` is causing the error. 

I've tried wrapping my head around why this is the case and haven't come to any plausible reason. 

Code of the files are the following:
**init.js**
```
const Jasmine = require('jasmine');
const reporters = require('jasmine-reporters');

/* Setup default reporting for jasmine */
var junitReporter = new reporters.JUnitXmlReporter({
    savePath: './reports/',
    consolidateAll: false
});
var jasmine = new Jasmine();
jasmine.loadConfigFile('spec/support/jasmine.json');
jasmine.addReporter(junitReporter);

/* Set default timeout for the test runner (in ms) */
jasmine.DEFAULT_TIMEOUT_INTERVAL = 999999;
jasmine.execute(['spec/test-actions.spec.js']);
```

**test-actions.spec.js**
```
describe("basic specs", function(){
	it("truthy-falsey", function(){
		expect(true).toBe(true);
	});
});
describe("asynchronous specs", function() {
  beforeEach(function(done) {
    done();
  }, 500);

  it("takes a long time", function(done) {
    setTimeout(function() {
      done();
    }, 2500);
  }, 10000);

  afterEach(function(done) {
    done();
  }, 500);
});
```

**Comment by slackersoft** [comment]
The `jasmine` command will boot up an Jasmine environment and `execute` it for you. If you want to do your own setup and `require('jasmine');` in your own code, you should _not_ use the executable that comes with this package.

Hope this helps. I'm going to close this since it doesn't sound like an issue with Jasmine itself. Thanks for using Jasmine!
