### ISSUE TITLE
Helper with wildcards broken on jasmine-npm@2.5.3

### ISSUE THREAD

**Issue by dexdexdex** [jasmine/jasmine-npm#105]
Hello friends-

We use jasmine in our builds and we discovered yesterday all the builds while executing grunt test. The command we usually do is:

```cmd
C:\Windows\system32\cmd.exe /s /c "node node_modules/istanbul/lib/cli.js cover --preserve-comments --include-all-sources --color --report cobertura --report lcov --root lib/ --dir build/coverage test/jasmine_runner.js -- --spec-folder test/ --helpers helpers/**/*.js --spec-matcher /**/*[sS]pec.js"
```

With jasmine-npm@2.5.3, we run into EPERM issues:
C:\Jenkins\workspace\Module - bfdata\node_modules\glob\sync.js:341
       throw er
             ^
Error: EPERM, operation not permitted 'C:\Documents and Settings'

I suspect the change that got in with helper cli messed things up with wildcards? 
https://github.com/jasmine/jasmine-npm/pull/75

**Comment by slackersoft** [comment]
None of the options you show in your command line exist in Jasmine. It look like you're executing a `jasmine_runner.js` file and passing it some options. What sort of Jasmine command line does that turn into?

**Comment by slackersoft** [comment]
We haven't heard anything more on this issue, and we don't have enough information about how Jasmine is being invoked to help diagnose this, so I'm going to close it for now. If you are still having issues, we'd be happy to look into them further with a bit more information.

Thanks for using Jasmine!
