### ISSUE TITLE
Can't run jasmine after npm install

### ISSUE THREAD

**Issue by inceva** [jasmine/jasmine-npm#115]
I still cannot run jasmine from the command line after npm installing it globally.

**> node -v**
v6.2.1

**> npm install -g jasmine**
`-- jasmine@2.5.3
  +-- exit@0.1.2
  +-- glob@7.1.1
  | +-- fs.realpath@1.0.0
  | +-- inflight@1.0.6
  | | `-- wrappy@1.0.2
  | +-- inherits@2.0.3
  | +-- minimatch@3.0.3
  | | `-- brace-expansion@1.1.7
  | |   +-- balanced-match@0.4.2
  | |   `-- concat-map@0.0.1
  | +-- once@1.4.0
  | `-- path-is-absolute@1.0.1
  `-- jasmine-core@2.5.2

**> jasmine .\Framework\Utility\Test\TestSpec.js**
jasmine : The term 'jasmine' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jasmine .\Framework\Utility\Test\TestSpec.js
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jasmine:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by slackersoft** [comment]
This sounds like a node.js/npm config issue on your machine. Possibly something like this: http://stackoverflow.com/questions/29955217/global-npm-package-installed-but-command-not-found

In the future you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing this. Thanks for using Jasmine!
