### ISSUE TITLE
Jasmine Cannot Find Spec Files

### ISSUE THREAD

**Issue by kariasbolster** [jasmine/jasmine-npm#117]
Hi I am having trouble on jasmine. I created a jasmine.json and these are the configurations:

```
{
  "spec_dir": "test",
  "spec_files": [
    "**/*.spec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": false
}
```

And this is my folder structure http://pasteboard.co/XjNjwc03.png

But when i run jasmine jasmine.json it cannot find the spec files. Can someone please explain to me why this is happening?

**Comment by agirorn** [comment]
You have to tell jasmine where the jasmine.json file is like this
```shell
jasmine JASMINE_CONFIG_PATH=jasmine.json
```

For more on this look at the [jasmine documentation](https://jasmine.github.io/2.6/node.html#section-18)

**Comment by slackersoft** [comment]
The default place that Jasmine looks for your `jasmine.json` file is in the current working directory. If you want it to live somewhere else, you should either use the `--config` option, or the `JASMINE_CONFIG_PATH` environment variable.

Hope this helps. Thanks for using Jasmine!

**Comment by kariasbolster** [comment]
Oh I see. Thanks guys for the help. Sorry the late reply I was writing front-end tests these past few days so I wasn't able to get back to this. I use jasmine for my backend api tests.
