### ISSUE TITLE
`jasmine` doesn't run

### ISSUE THREAD

**Issue by nmaxcom** [jasmine/jasmine-npm#118]
I installed first with `yarn`. Then cleaned and went with `npm`, manual verbatim. Same results:

`command not found: jasmine`

I tried the alternate: `node_modules/.bin/jasmine`
Treason! Because that previous command and the next one are not the same:

![image](https://cloud.githubusercontent.com/assets/8936090/25650427/1205311c-2fdd-11e7-8d8d-50c53e58ad72.png)

So... Why? And how to fix it "your way"?

**Comment by agirorn** [comment]
If you run `npm install jasmine` or If jasmine is a dependency / devDependcy in your package.json and you have run `npm install`, jasmine is installed into the local node_modules folder and then you can run jasmine like this `node_modules/.bin/jasmine`. 

if you install it globally `npm install jasmine -g` then can run it like this `jasmine`. 

Yarn should work exactly the same.

**Comment by slackersoft** [comment]
The Node.js getting started section of our docs should probably change to match the realities of the package management system. I'm not totally sure which should be the suggested option though.

I think in general that Jasmine should probably be installed as a devDependency of an individual codebase so different apps can use different versions if needed. Unfortunately, this means that you have to use the `node_modules` path (or use it in a script in your `package.json`). If you install globally, you'll be able to run `jasmine` without any path qualifiers, but you'll only have one available.

I'm leaning toward updating the getting started guide to do `./node_modules/.bin/jasmine init` and then set `"jasmine"` as the `test` script in your `package.json` so you'd run tests with `npm test`, but I'm open to other options.

Hope this helps. Thanks for using Jasmine!

**Comment by nmaxcom** [comment]
@agirorn I'm afraid you are missing the point

@slackersoft 

> The Node.js getting started section of our docs should probably change to match the realities of the package management system. I'm not totally sure which should be the suggested option though.

Yes, it should be changed. Details aside, just follow a simple rule: do not fool your future users.

Thanks for developing Jasmine.

**Comment by robertpak1** [comment]
I did a global install and still can't get jasmine to run.
I try a check: jasmine -v
and get back -bash: jasmine: command not found

**Comment by slackersoft** [comment]
@robertpak1 It sounds like your PATH doesn't include wherever you have npm installing global packages. Try running `npm prefix -g` and make sure that path is included if you `echo $PATH`.

Hope this helps.
