### ISSUE TITLE
How to check children method has been called in jasmine?

### ISSUE THREAD

**Issue by thirusabari** [jasmine/jasmine-npm#126]
Hai! We use `spyOn(this,"_new")` to track a function call in jasmine.  I need to check the children method call in jasmine. My code sample is given below,

Sample code:-

    function perform(option)

     {

               this.answer=this.perform._sum(option.a+option.b);

               console.log(this.answer);

     }

My question is how to check the `this.perform.sum(option.a+option.b)` has been called with `spyOn()` in jasmine JavaScript?

I have tried the below way, but it was not worked as much I expected?

      it("If we pass  arguments to the perform method, ensuring that sum method has been called or 
                       not",function(done){

                       spyOn(this,"perform._sum");

                       var option={a:10,b:6};

                       this.perform(option);

                       expect(this.perform._sum).toHaveBeenCalledWith(option.a,option.b);

                       done();
       });

But above code was not worked. Can anybody tell me, how to check the children method call in jasmine using `spyOn()` ?

Regards,
Creator

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Closing. Thanks for using Jasmine!
