### ISSUE TITLE
Exit code always returns '0', no matter tests results

### ISSUE THREAD

**Issue by Remi-p** [jasmine/jasmine-npm#127]
Hello,

As part of our CI tasks we're using `jasmine-npm` in my organization.
We realized recently that no matter what the tests results were, the exit code of the command was always `0`.

I added some `console.log` in the `lib/exit.js` function. Results in console are below.

With no tests failing:
```console
> JASMINE_CONFIG_PATH=jasmine.json ./node_modules/.bin/jasmine; echo $?
Started
........

Ran 8 of 176 specs
8 specs, 0 failures
Finished in 0.083 seconds

exitCode: 0
platform: darwin
nodeVersion: v8.7.0
exit(0)

0
```

With failing tests:
```console
> JASMINE_CONFIG_PATH=jasmine.json ./node_modules/.bin/jasmine; echo $?
Started
[...]

176 specs, 21 failures
Finished in 3.177 seconds

exitCode: 1
platform: darwin
nodeVersion: v8.7.0
exit(1)

0
```

I realized manually setting `process.exitCode` in `checkExit()` function of `jasmine.js` worked... See this commit https://github.com/Remi-p/jasmine-npm/commit/e09547a4357761f2299256c492e11cfcc45e223e .

Thanks !

**Comment by slackersoft** [comment]
Can you supply a small example suite that demonstrates this? The `checkExit` function is only really used in the case when something has called `exit` before the jasmine suite has completed. Normal suite completion should call `exitCodeCompletion` above that will explicitly call `exit` with the code to exit with.

Thanks for using Jasmine!

**Comment by Remi-p** [comment]
Oops, actually it was our fault...

We did a
```javascript
process.exit = jasmine.createSpy('exit');
```
to check that `process.exit()` was correctly called in our application...
But this way, it wasn't possible to correctly exit the tests !

Thanks for your reply.
