### ISSUE TITLE
Disable stackTrace output for failed cases

### ISSUE THREAD

**Issue by quintuschen** [jasmine/jasmine-npm#133]
While a test case fails we will have a failure message like the following

    Failures:
    1) Should validate labels
        Message: 
          Failed: xxx
        Stack:
          xxxx
          xxxx
          xxxx
          xxxx
          ...

Sometimes the stack trace is really and it can take up pages to display, which could potentially ruin the reporter when trying to display the failed messages.

I have tried:

    protractor conf.js --no-stackTrace

Previously in older version of jasmine we could disable it by setting:

    jasmineNodeOpts: {
        defaultTimeoutInterval: 30000,
        includeStackTrace: false,
    }

It could be nice for jasmine-npm to be able to disable stackTrace as well.

**Comment by slackersoft** [comment]
It looks like the old [jasmine-node](https://github.com/mhevery/jasmine-node) package included the option to suppress all stack traces at the reporter level, but this isn't a feature that Jasmine itself includes. 

What about the stack traces is too long? As of Jasmine 3.0 any Jasmine lines in the stack trace should be elided behind a single `<Jasmine>` line to help collapse out some of the noise. I'm not sure what version of Jasmine protractor supports at this time (there were some other reporter changes in 3.0 as well), but you might look there to see if a newer version of Jasmine cleans up the stack traces a bit for you.

Hope this helps. Thanks for using Jasmine!

**Comment by quintuschen** [comment]
Thanks for your reply @slackersoft , I checked that the latest Protractor I am using is 5.3.2, which uses Jasmine 2.8.0, and the repo it uses is "git+https://github.com/jasmine/jasmine-npm.git". 

I tried to install Jasmine 3.1.0 for protractor but it still gives a lot of stack trace when a case failed. Do I still need to pass --no-stackTrace or set includeStackTrace to false?

Thank you!

**Comment by quintuschen** [comment]
Thanks. I understand. I'll think about other ways to reduce the stack trace in the display. :)
