### ISSUE TITLE
Process exit code is not consistent

### ISSUE THREAD

**Issue by elliot-nelson** [jasmine/jasmine-npm#137]
When running jasmine from command line, I would expect to receive a non-zero exit code any time the result isn't a successful test pass.  It doesn't look like this is always true though: for example, if you specify an invalid argument to jasmine (`jasmine --zebra`), it prints an error and usage help, but exits with exit code `0`.

Proposal: ensure that any situation that isn't a green test pass returns exit code > 0.  This would include a test failing, no tests found, an invalid argument, or any other exception in the jasmine library itself.

**Comment by slackersoft** [comment]
This sounds totally reasonable. We've tried to cover most of the cases, but probably missed a few. I would be happy to review a pull request to add explicit exit codes for some of the places that are non-success.

**Comment by elliot-nelson** [comment]
Sounds good!

Actually, it looks like maybe there is only this one hole, since the exit handler covers all the cases where jasmine-core itself fails.  I'll put something up and see what you think.
