### ISSUE TITLE
Exclude node_modules from spec_files

### ISSUE THREAD

**Issue by gustavofp** [jasmine/jasmine-npm#143]
I'm in trouble excluding node_modules files from my spec_files option.

This is my jasmine.json config.
`{
  "spec_dir": "packages",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": true
}`

the spec_dir is a directory with multiple node_projects, each one has their own node_modules folder.

I've tried add '!node_modules/**/*[sS]pec.js' on the spec_files array but didn't work.

Is that a bug? Because from what i read in the docs thats the way I can exclude files from spec coverage.

Thanks!

**Comment by slackersoft** [comment]
Sorry for the confusion. The exclusion functionality isn't in the 3.2 release of Jasmine, but was still waiting to be released. I just finished releasing Jasmine 3.3, which should include this feature and a number of other things.

Hope this helps. Thanks for using Jasmine!

**Comment by RenaudF** [comment]
In case this can help anyone else bumping into this issue: https://stackoverflow.com/questions/52937171
