### ISSUE TITLE
Website claims Jasmine has no dependencies, yet the jasmine npm package depends on Glob

### ISSUE THREAD

**Issue by ashelleyPurdue** [jasmine/jasmine-npm#148]
And glob, in turn, depends on:
* fs.realpath 
* inflight
* inherits
* minimatch
* once
* path-is-absolute
* wrappy
* brace-expansion
* balanced-match
* concat-map

That just seems a little bit misleading.

**Comment by slackersoft** [comment]
That's fair, the docs page is referring more to jasmine-core which doesn't have any runtime dependencies. We strive to keep the dependencies of the other libraries as small as possible, but trying to re-implement `glob` in a manner consistent with what everyone expect didn't seem like it was worth it.

What would you recommend that wording be changed to?

**Comment by ashelleyPurdue** [comment]
"jasmine-core has no dependencies" would be nice.
