### ISSUE TITLE
Please add --fail-fast support

### ISSUE THREAD

**Issue by nertzy** [jasmine/jasmine-npm#16]
It would be great to be able to exit on the first spec failure and see its output. It would greatly speed up my testing workflow.

**Comment by amavisca** [comment]
This is something we'd be open to a pull request for in the core, for all of jasmine to access. We've got an issue opened for it here: https://github.com/jasmine/jasmine/issues/414.

**Comment by F1LT3R** [comment]
+1

With Protractor we used to be able to use `realtimeFailure` before, is this no longer available?

```
  jasmineNodeOpts: {
    realtimeFailure: true,
 }
```

**Comment by slackersoft** [comment]
This functionality is in Jasmine 3.0. Use `--fail-fast=true`

Closing. Thanks for using Jasmine!

**Comment by alexch** [comment]
https://github.com/jasmine/jasmine/issues/1563
seems this isn’t quite working yet
