### ISSUE TITLE
Load-time errors are ignored if --worker-count is greater than 1.

### ISSUE THREAD

**Issue by sgravrock** [jasmine/jasmine-npm#165]
Steps to reproduce:

1. Create a spec file that throws an exception when loaded, and make sure it matches the `spec_files` glob.
2. Run `jasmine --worker-count=2`.

Expected: Jasmine exits nonzero.
Observed: Jasmine prints the exception, reports the following, and exits zero:

```
No specs found
Finished in NaN seconds
```

**Comment by slackersoft** [comment]
Multiple worker functionality has been removed
