### ISSUE TITLE
the message when test passed is not good looking.

### ISSUE THREAD

**Issue by chenliangyu** [jasmine/jasmine-npm#17]
when test passed, message only have a green dot. why don't do it like jasmine-node?
i prefer to use jasmine-npm just because it's official.and the version of jasmine is latest.

**Comment by slackersoft** [comment]
The default reporter for jasmine-npm with the simple `ConsoleReporter` that prints `.` and `F` for passes and failures and will print out the failure information at the end of the run. If you want different output, you can call `addReporter` and jasmine will use that instead.

Closing.
