### ISSUE TITLE
Should `jasmine init` include `.mjs` in output?

### ISSUE THREAD

**Issue by jakub-g** [jasmine/jasmine-npm#176]
When doing `jasmine init` it reads an example file:
https://github.com/jasmine/jasmine-npm/blob/main/lib/command.js#L143

which currently puts `"**/*[sS]pec.js"` to `spec_files`:
https://github.com/jasmine/jasmine-npm/blob/a91e8d4a97a4241ab04cc531ebfe917c618a208c/lib/examples/jasmine.json#L4

I'm wondering if it should output `"**/*[sS]pec.(m?)js"` now since jasmine supports mjs? WDYT?

(Also, perhaps the docs should be updated: https://jasmine.github.io/setup/nodejs.html#using-the-library)

**Comment by sgravrock** [comment]
That sounds good. I'd be happy to review a pull request that makes that change.
