### ISSUE TITLE
Add logging options

### ISSUE THREAD

**Issue by AustP** [jasmine/jasmine-npm#18]
When running jasmine-npm, every success just prints a `.`. It would be nice if I could see the specs outputted like it is on jasmine.github.io

    A suite
      contains spec with an expectation

    A suite is just a function
      and so is a spec

    The 'toBe' matcher compares with ===
      and has a positive case
      and can have a negative case

**Comment by slackersoft** [comment]
It should be possible to just write your own custom reporter and tell jasmine to use that. Additionally, I'd be happy to review a pull request to augment the `ConsoleReporter` to be configurable about what the output looks like.

**Comment by AustP** [comment]
@slackersoft I found the [jasmine-node](https://github.com/mhevery/jasmine-node) project and it already has the verbose options as well as many others. I'm just gonna use that project.
