### ISSUE TITLE
Can I use jasmine without jasmine.json?

### ISSUE THREAD

**Issue by elgs** [jasmine/jasmine-npm#181]
Basically I want run jasmine command and it will run all `*spec.js` under `spec` directory. But I hate to maintain `jasmine.json` as another config file. I wonder if there's any default values for like `spec_dir` and `spec_files`. I'd love to follow the default values, if any. I will never want to customize them. Even command line argument like `npx jasmine -spec_dir spec` would be great to me. Thanks.

**Comment by sgravrock** [comment]
Nowadays `npx jasmine spec/**/*.js` works for running all specs in a directory without a config file. (Or with quotes, `npx jasmine 'spec/**/*.js'` if you're using a shell that doesn't do bash-compatible file globbing.)
