### ISSUE TITLE
Command line options

### ISSUE THREAD

**Issue by paazmaya** [jasmine/jasmine-npm#19]
Please make available command line options such as `-V` for version, `-h` for help, `-c` for configuration file.
There seems to be help available as `jasmine help`, but since "most" command line tools used the dashed version, perhaps jasmine could too.

There are several extensions that make it easy to configure these command line options, such as `nomnom` or `yargs`.

Also I would like to specify `specDir` and possible `helpers` directory via command line.

**Comment by amavisca** [comment]
I've added a story to the tracker for options like -h and -v.
https://www.pivotaltracker.com/story/show/87856068

We already allow you to pass files/folders in the command line, but the implementation is a bit weird. I've added a story [here](https://www.pivotaltracker.com/story/show/87859994) to address some of that.

**Comment by slackersoft** [comment]
This should be fixed now on master, and have a bit better reference in the help as well.

Closing. Thanks for using jasmine!
