### ISSUE TITLE
Reporter not compatible with WebStorm

### ISSUE THREAD

**Issue by inf3rno** [jasmine/jasmine-npm#20]
The reporter is not compatible with WebStorm, I got only `...FFF.....F..` etc... in the console, but no failure details. I checked, in nodejs it runs properly.

**Comment by inf3rno** [comment]
Not compatible with jasmine-node tests either, but without details it's hard to find out what's the problem, 
- `has no method andCallThrough` - hmm interesting, do the spies work differently?
- ` 'expect' was used when there was no current spec, this could be because an asynchronous test timed out` - this is interesting either, I don't have asnyc tests, I installed jasmine2 instead of jasmine-node, because I wanted better async test support before I start to write async tests... :S

**Comment by inf3rno** [comment]
The new line is okay, it prints a single one before the `...FFF.....F..`. The tests are okay either, they don't kill the test runner, so I guess it exits too early, or it is set to non-verbose mode if such a thing exists.

**Comment by inf3rno** [comment]
The problem that `jasmineDone` never runs in the reporter.

**Comment by inf3rno** [comment]
`'expect' was used when there was no current spec, this could be because an asynchronous test time, ...` was because jasmine-node allows to put tests in `describe`, while jasmine allows them only in `it`

**Comment by inf3rno** [comment]
Here is what I got in webstorm:
![nevtelen](https://cloud.githubusercontent.com/assets/408911/6012758/3eadfa5e-ab4c-11e4-989b-055512ff96b5.png)
and here is what I got in bash:
![nevtelen2](https://cloud.githubusercontent.com/assets/408911/6012763/560d7c60-ab4c-11e4-928f-07902cb2e69d.png)

**Comment by inf3rno** [comment]
I created an issue by webstorm as well: https://youtrack.jetbrains.com/issue/WEB-15046

**Comment by inf3rno** [comment]
I think I was wrong. I added `console.log("x")` to the first line, and it sometimes prints the `x`, sometimes not. So this might be a timeout issue.

**Comment by inf3rno** [comment]
I think WebStorm forces the nodejs to close, or something like this happens. With a single test only it does not print anything. So it depends on the test count.

**Comment by inf3rno** [comment]
Nope, I checked with `fs.appendFileSync`. The `reporter.jasmineDone` runs until the end every time, so the tests run, but the console stops working in the middle of the printing. I don't know what causes this. :S

**Comment by inf3rno** [comment]
I modified this part: https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L28

```js
Jasmine.prototype.configureDefaultReporter = function(options) {
  var defaultOnComplete = function(passed) {
    if(passed) {
      process.exit(0);
    }
    else {
      process.exit(1);
    }
  };

    var customLogger = {
        data: "",
        log: function (message){
            this.data += message;
        },
        close: function (){
            process.stdout.write(this.data);
        }
    };

  options.timer = options.timer || new this.jasmine.Timer();
  options.print = options.print || function() {
    //process.stdout.write(util.format.apply(this, arguments));
      customLogger.log(util.format.apply(this, arguments));
  };
  options.showColors = options.hasOwnProperty('showColors') ? options.showColors : true;
  options.onComplete = function (){
        customLogger.close();
      (options.onComplete || defaultOnComplete).apply(this, arguments);
  };
  options.jasmineCorePath = options.jasmineCorePath || this.jasmineCorePath;

  var consoleReporter = new module.exports.ConsoleReporter(options);
  this.addReporter(consoleReporter);
};
```

I added a `customLogger`, which prints the results only once. Now I got the following with a single file, single failing test:

```
bject.<anonymous> (d:\creation\software developer\projects\dflo2\spec\x.spec.js:4:22)

1 spec, 1 failure
Finished in 0.006 seconds
Started
F

Failures:
1) example fails
  Message:
    Expected true to be false.
  Stack:
    Error: Expected true to be false.
        at Object.<anonymous> (d:\creation\software developer\projects\dflo2\spec\x.spec.js:4:22)

1 spec, 1 failure
Finished in 0.006 seconds
Started
F

Failures:
1) example fails
  Message:
    Expected true to be false.
  Stack:
    Error: Expected true to be false.
        at Object.<anonymous> (d:\creation\software developer\projects\dflo2\spec\x.spec.js:4:22)

1 spec, 1 failure
Finished in 0.006 seconds
Started
F
....
```

It is a very long list, it runs the test more than 100 times....

**Comment by inf3rno** [comment]
With more tests I got the following:

```
"C:\Program Files (x86)\JetBrains\WebStorm 9.0.3\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" c:\Users\inf3rno\AppData\Roaming\npm\node_modules\jasmine\bin\jasmine.js
Started
.........................F

Failures:
1) example fails
  Message:
    Expected true to be false.
  Stack:
    Error: Expected true to be false.
        at Object.<anonymous> (d:\creation\software developer\projects\dflo2\spec\x.spec.js:4:22)

26 specs, 1 failure
Finished in 0.034 seconds

buffer.js:278
  return b instanceof Buffer;
           ^
RangeError: Maximum call stack size exceeded

Process finished with exit code 8

```

**Comment by inf3rno** [comment]
Shit happens! :D I don't have the time to find out how fix this, but I guess I provided enough information to you to do it.

**Comment by inf3rno** [comment]
Hmm modifying the Reporter should work either. So I think a different Reporter subclass is the good solution. I'll add the new Reporter class asap.

**Comment by inf3rno** [comment]
I reverted jasmine.js, and modified https://github.com/jasmine/jasmine-npm/blob/master/lib/command.js#L65 instead:

```js
function runJasmine(jasmine, env) {
  jasmine.loadConfigFile(process.env.JASMINE_CONFIG_PATH);

  var report = "";
  jasmine.configureDefaultReporter({
    showColors: env.color,
    print: function() {
        report += util.format.apply(this, arguments);
    },
    onComplete: function(passed) {
        process.stdout.write(report);
        if(passed) {
            process.exit(0);
        }
        else {
            process.exit(1);
        }
    }
  });
  jasmine.execute(env.files);
}
```
I think it is sad, that currently we cannot configure the default reporter in the config file. This whole code should be placed there as something exceptional.

**Comment by slackersoft** [comment]
Based on your investigation, this sounds like an issue with WebStorm terminating the `jasmine` command early and not jasmine-npm itself. Closing.

Thanks for using jasmine!

**Comment by inf3rno** [comment]
You are right, I think it is a WebStorm issue. It does not terminate the command, but its console stops receiving the printed data. I had the same issue with PHPStorm and SimpleTest (an old PHP testing framework). I'll check the code of jasmine-node, maybe there is a known solution in there, because jasmine-node worked properly with these IDEs. I'll write back if I find something. I'll add a feature request about the custom reporter.

**Comment by inf3rno** [comment]
https://youtrack.jetbrains.com/issue/WEB-1926
It seems to be a 3 years old windows + nodejs issue which will be fixed in Node.js v0.11.12 I have the 0.10.36 now. That's all.

**Comment by inf3rno** [comment]
I have found the perfect workaround. Just replace this line: https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L43
```js
options.onComplete = options.onComplete || defaultOnComplete;
```
with this:
```js
  options.onComplete = (function (onComplete) {
      return function (){
          var context = this;
          var args = arguments;
          setTimeout(function (){
                onComplete.apply(context, args);
          },1);
      };
  })(options.onComplete || defaultOnComplete);
```
If you have the same issue on windows. It simply defers the exit with 1ms. That seems to be enough time to end the printing. Good day, ciao!

**Comment by segrey** [comment]
Another workaround is to use https://github.com/cowboy/node-exit instead of `process.exit` as some other node console tools (e.g. grunt) do.

**Comment by inf3rno** [comment]
Nice, it appears to be complicated to exit properly in node :D 
https://github.com/cowboy/node-exit/blob/master/lib/exit.js

Thanks segrey!

**Comment by amavisca** [comment]
@segrey Thanks for the workaround, I pulled in the exit module.
