### ISSUE TITLE
Custom reporter

### ISSUE THREAD

**Issue by inf3rno** [jasmine/jasmine-npm#21]
I think it would be much easier to solve compatibility issues (like [this](https://github.com/jasmine/jasmine-npm/issues/20)) if we will be able to configure the reporter from the config file (so we would not have to modify the code itself). Having at least the `print` and `onComplete` config options would be great.

**Comment by rubennorte** [comment]
I also had problems related with this yesterday. Jasmine by default adds a console reporter with an `onComplete` callback that exits the process. This causes Jasmine to never call "jasmineDone" on next reporters, so they become useless. I think an elegant solution for this would be adding a "--no-default-reporter" option to the CLI tool.

**Comment by arusakov** [comment]
May be execute Console Reporter after other reporters?
But flag "--no-default-reporter" is a great idea too.

**Comment by slackersoft** [comment]
When we were setting up jasmine-nom, we didn't envision anyone adding a reporter as a "helper" file. In retrospect, it makes sense for users to want to do that. So jasmine-npm, should probably wait until after all helper files are loaded to determine whether to add its `ConsoleReporter`.

We'd be happy to review a pull request that allowed a reporter added in a helper file via jasmine-npm's `addReporter` function (not jasmine-core's) to pre-empt adding of the default `ConsoleReporter`.

**Comment by inf3rno** [comment]
Thanks slackersoft! :-)

**Comment by ybian** [comment]
Does anyone have an example on how to remove the default console reporter by adding one in a helper file? I've spent hours but still fail to get it work. What I added in a helper file `spec/helpers/console_reporter.js`:

```
var util = require('util');

options = {
  showColors: true,
  print: function() {
    return process.stdout.write(util.format.apply(this, arguments));
  },
  stackFilter: function(stack) {
    return 'test stack filter';
  }
};

jasmine.getEnv().addReporter(new jasmine.ConsoleReporter(options));
```

But the default console reporter is still used while running `jasmine`, and the added one is not called at all. Debugging shows that `jasmine` in the helper script is actually `jasmine-core`, and its `addReporter` method does not incremental `reportersCount` variable of `jasmine-npm`. So in the following check `reportersCount` is 0 and the default one is still added:

```
Jasmine.prototype.execute = function(files, filterString) {
  this.loadHelpers();

  if(this.reportersCount === 0) {
    this.configureDefaultReporter({ showColors: this.showingColors });
  }
```

This only explains part of the issue I met. I still don't understand why the newly added reporter does not take effect.

Did I miss something obvious?

**Comment by slackersoft** [comment]
We've just changed how the default reporter is set up, you should be able to `clearReporters()` for the underlying jasmine environment to get rid of the default reporter and only use your own.

Hope this helps. Thanks for using Jasmine!
