### ISSUE TITLE
Add a `--verbose` flag

### ISSUE THREAD

**Issue by DanKaplanSES** [jasmine/jasmine-npm#211]
This could save a lot of time when troubleshooting unexpected behavior. I was trying to set up a new project and went through this experience:

1. I created a spec with `expect(true).toBe(false);` and ran `jasmine`.
1. Why does it say no specs found? _Where is it looking?_
3. _Does the command line have a `--verbose` flag (or equivalent)?_ No. Not that I can find. 
4. Then I googled. I couldn't find anything relevant, but some of the links gave me ideas.
5. I had set "spec_dir" to `""`, `"."`, `"/"`, and `"./"`—something I've never done before. _Is this a bug of some sort, where Jasmine doesn't scan for specs in the same directory as "spec_dir"?_
6. No, because I created a subdirectory and put a spec in there. It couldn't find it either. _Is this a limitation of some sort, where you can't specify a "spec_dir" at the project root?_
7. No, because...
8. _Is my config file *actually* being used?_
9. **No. My config file isn't named `jasmine.json`, so jasmine won't use it by default. That's the problem.**

I've run into similar problems in the past where a `--verbose` flag would've helped so I'd like to request this as a feature. Thanks

---

```
jasmine v5.1.0
jasmine-core v5.1.1
```

**Comment by sgravrock** [comment]
That seems like a nice feature to have. I'd be happy to review a PR that adds it.
