### ISSUE TITLE
onComplete() is never fired in a Grunt task

### ISSUE THREAD

**Issue by onury** [jasmine/jasmine-npm#22]
I've built a very simple Grunt task for Jasmine (Node) based on the task example. But `onComplete()` callback is never fired in the Grunt task (so does the `done()` method). Am I missing something?

```js
module.exports = function (grunt) {
    'use strict';

    var Jasmine = require('jasmine');

    grunt.registerTask('jasmine_task', function () {
        var jasmine = new Jasmine(),
            done = this.async();

        jasmine.configureDefaultReporter({
            print: function () {
                grunt.log.writeln.apply(this, arguments);
            },
            onComplete: function (passed) {
                done(passed);
            }
        });

        var specFiles = grunt.file.expand('test/node/unit/**/*spec.js');
        jasmine.execute(specFiles);
    });
};
```
If not inside a Grunt task, this code works as expected.

Mac OS X Yosemite (10.10.2)
Node v0.10.22
grunt-cli v0.1.13
grunt v0.4.5

**Comment by amavisca** [comment]
I wasn't able to reproduce this.

I used `jasmine init` and `jasmine examples` in an empty folder, and then copied your code as my Gruntfile.

What version of the jasmine module are you using? Do you have any other output/examples you can share to help us reproduce this?

**Comment by onury** [comment]
Hi, I've found out that it was a conflict with a left-over node package (grunt-jasmine-node-coverage). My own task started working properly after I removed that.

By the way, the NPM package is not sync'ed with this repo. It does not have the `exit` module update.

Closing this now, thanks.

**Comment by amavisca** [comment]
@onury We pushed 2.2.1 to npm with the exit fix.

**Comment by onury** [comment]
Thanks @amavisca.
I've published [grunt-jasmine-nodejs](https://github.com/onury/grunt-jasmine-nodejs) for the latest Jasmine; if anyone needs it.
