### ISSUE TITLE
customer reporter not finishing 

### ISSUE THREAD

**Issue by bennage** [jasmine/jasmine-npm#23]
I'm having a problem that seems related to #20, but I think that it may be different.

I'm trying to setup a simple Growl reporter. (Maybe there's already one out there that you can recommend?) I'm using __2.2.1__.

My problem is this:
In the [`execute` method](https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L104) of the wrapper that `jasmine-npm` creates around `jasmine-core`, it checks the `reportersCount` property and sets up the default reporter is the value is `0`. The value of `reportersCount` is only modified in `addReporter`.

The instance of `jasmine` in my custom report is the one that is being wrapped. This means that I am not able to use the method that bumps `reportersCount`. In turn, `configureDefaultReporter ` is always called. (I actually do want the `ConsoleReporter` to be added to, but I think that it's `onComplete` is terminating everything before my customer reporter is done.)

The end result is that `jasmineDone` is never called on my customer reporter.

My implementation (es6) is here:
https://gist.github.com/bennage/10bc25cdcc869bdbd92f

Any help is greatly appreciated.

**Comment by amavisca** [comment]
You shouldn't do that in the reporter itself, you should make a script/grunt task/gulp task.

You can instantiate a new instance of your reporter somewhere and give it to jasmine.

```
var Jasmine = require('jasmine');
var GrowlReporter = require('./growlReporter');

var jasmine = new Jasmine();
//or wherever your config file is, you can use .loadConfig to pass in an object instead of a file
jasmine.loadConfigFile('support/jasmine.json'); 
// add your custom reporter
jasmine.addReporter(new GrowlReporter());
// adds the console reporter
jasmine.configureDefaultReporter(); 
jasmine.execute();
```

The jasmine you used in the GrowlReporter refers to the [jasmine-core](http://npmjs.org/package/jasmine-core), which the `jasmine` module wraps.

Let me know if this answered your questions!

**Comment by bennage** [comment]
Yes, it does help. I encourage to add this to the readme.
I had `npm test` pointing to `jasmine` and I had simply put `growlReport.js` in the `helpers` directory.
Thanks for your time.
