### ISSUE TITLE
Helper functions not loading

### ISSUE THREAD

**Issue by travisperson** [jasmine/jasmine-npm#25]
It appears that the helpers folder should be in the folder defiend by `spec_dir`, I've also tried though with the helpers folder at the root right along side `spec_dir`.

*./spec/support/jasmine.json*
```json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ]
}
```

*./spec/spec.js*
```javascript
describe('Include helpers', function () {
    it('should have foo defined', function () {
        expect(typeof foo).toBe('function')
    })
})
```

*./spec/helpers/test_helper.js*
```javascript
module.exports = {
    foo: function () {
        return 'bar';
    }
}
```

This fails

```
~/t/test $ cat ~/local/lib/node_modules/jasmine/package.json | grep version
  "version": "2.2.0",
~/t/test $ jasmine
Started
F
 
Failures:
1) Include helpers should have foo defined
  Message:
    Expected 'undefined' to be 'function'.
  Stack:
    Error: Expected 'undefined' to be 'function'.
        at Object.<anonymous> (/home/tperson/tmp/test/spec/spec.js:3:28)
 
1 spec, 1 failure
Finished in 0.004 seconds
~/t/test $ 
```

https://gist.github.com/travisperson/328381f4ea9a7deac3f2

**Comment by amavisca** [comment]
A helper file is really just code that is executed right before the specs are run.

Each spec has`this` bound to an object that can be used across that spec (including in the beforeEach/beforeAll/etc.). 

You can set your helper functions/objects in a `beforeEach` in your helper:
```
beforeEach(function() {
  this.sum = function(a, b) { return a + b };
  // this.difference = require('./helpers/difference');
});
```

and then use them in the `it` in your spec file:

```
it('can use helpers', function() {
  expect(this.sum(1, 2)).toEqual(3);
});
```

Alternatively, you could put them on the global object since the helper files and spec files share a global object.

You could also just require them in yourself in your spec files as you need them.

**Comment by travisperson** [comment]
Thanks, this looks good. Though I'd assume you'd want to only use a beforeAll to only ever include the helpers once across all first level `describes`?

**Comment by slackersoft** [comment]
Helper files are really designed to allow you to add a global `beforeEach`, `afterEach`, etc. Or to add a matcher that should be available to your full suite.

If you want to define a function in a helper file that is globally available, you would need to put the function on the `global` object, as @amavisca mentioned.

It doesn't look like this is actually an issue with jasmine itself, so I'm going to close it. Feel free to re-open if there is still an issue.

**Comment by Izhaki** [comment]
Worth noting that if you are using typescript with fat arrow (`() =>`), you won't get the right `this` in your jasmine blocks when using helpers (you may get away with it otherwise).

Use `function(){}` instead for `this` to work, or don't use helpers.

**Comment by jmaton** [comment]
> Worth noting that if you are using typescript with fat arrow (`() =>`), you won't get the right `this` in your jasmine blocks when using helpers (you may get away with it otherwise).
> 
> Use `function(){}` instead for `this` to work, or don't use helpers.

Thank you!
