### ISSUE TITLE
Jasmine + Supertest

### ISSUE THREAD

**Issue by svileng** [jasmine/jasmine-npm#31]
I'm using [supertest](http://github.com/visionmedia/supertest) for testing Express applications. I found that `jasmine` totally breaks `supertest`'s expect matchers — there are no errors, everything just passes with green, even when the assertion is false. When I replaced `jasmine` with `mocha`, `supertest` started working as expected.

```
"express": "^4.11.2",
"supertest": "^0.15.0"`
```

**Comment by slackersoft** [comment]
Jasmine puts it's `expect` function on the global object to make the interface more fluent. I don't think mocha ships with the `expect()` syntax by default, so it's possible this is why supertest works with mocha. I'm not sure what supertest is doing that causes it to not work with jasmine.

**Comment by svileng** [comment]
@slackersoft Yes, I'm also using chai's `expect` with mocha: http://chaijs.com/guide/styles/#expect. I will post that in the supertest issue tracker, and see what they think.

**Comment by amavisca** [comment]
I assume it's the done callback.

The done function in jasmine doesn't take an error argument. You can pass an error argument to done.fail. The example on supertest's README using jasmine would be:

```
var request = require('supertest')
  , express = require('express');

var app = express();

app.get('/user', function(req, res){
  res.send(200, { name: 'tobi' });
});

describe('GET /users', function(){
  it('respond with json', function(done){
    request(app)
      .get('/user')
      .set('Accept', 'application/json')
      .expect('Content-Type', /json/)
      .expect(200, done.fail);
  })
})
```

**Comment by svileng** [comment]
Hi @amavisca  — I replaced `done` with `done.fail`, but the tests fail, when they should pass:

```javascript
it("routes public folder", function(done) {
    request(this.app).get("/favicon.ico").expect(200, done.fail)
})
```
```
Failures:
1) Setup express routes public folder
  Message:
    Failed
  Stack:
    Error: Failed
        at Test.assert (/Users/Svilen/Development/testapp/node_modules/supertest/lib/test.js:221:6)
        at Server.assert (/Users/Svilen/Development/testapp/node_modules/supertest/lib/test.js:132:12)
        at Server.g (events.js:199:16)
        at Server.emit (events.js:104:17)
```

**Comment by amavisca** [comment]
I see. `done()` is the success case and `done.fail(err)` is the fail case for jasmine. It looks like you'd have to handle that logic yourself using a `.end` from supertest since `done` can't take an error. Here's a github issue in the core jasmine repo about done: https://github.com/jasmine/jasmine/issues/567.

**Comment by svileng** [comment]
Right, got it. A node-style callback would be ideal, so I'll stick to `mocha` for my backend tests. Thanks for the taking the time to help :+1:

**Comment by washimimizuku** [comment]
I know you gave up on Jasmine for this, but there is a way, I took some time to figure it out. This is my code which works:

    var supertest = require('supertest');

    describe('DashboardController', function() {
      describe('Going to Dashboard without logging in', function() {
        it('should redirect to /backoffice/user/login', function (done) {
          supertest(sails.hooks.http.app)
            .get('/backoffice/dashboard')
            .expect(302)
            .expect('Content-Type', /text/)
            .expect('location','/backoffice/user/login')
            .end(function(err, res) {
              if (err) {
                done.fail(err);
              } else {
                done();
              }
            });
        });
      });
    });

So, to make it work, on the end of all the supertest describe's, you just put:

    .end(function(err, res) {
      if (err) {
        done.fail(err);
      } else {
        done();
      }
    });

And you do get a nice description on the console in case of error:

    .F.

    Failures:
    1) DashboardController Going to Dashboard without logging in should redirect to /backoffice/user/login
      Message:
        Failed: expected 200 "OK", got 302 "Moved Temporarily"
      Stack:
        Error: expected 200 "OK", got 302 "Moved Temporarily"
            at Test.assert (/somewhere/node_modules/supertest/lib/test.js:205:17)
            at Server.assert (/somewhere/node_modules/supertest/lib/test.js:131:12)
            at Server.g (events.js:199:16)
            at Server.emit (events.js:104:17)
            at net.js:1409:10
            at process._tickDomainCallback (node.js:381:11)

    3 specs, 1 failure
    Finished in 2.828 seconds

I'm doing this on sails.js, but should be exactly the same on express.js.

**Comment by svileng** [comment]
@washimimizuku Nice!! Thanks for the tip!

**Comment by noahsw** [comment]
+1 @washimimizuku !

**Comment by henrytseng** [comment]
+1 @washimimizuku

**Comment by nesQuick** [comment]
we use the following helper

```js
function finish_test (done) {
  return function (err) {
    if (err) {
      done.fail(err)
    } else {
      done()
    }
  }
}
```

example test:
```js
it('should respond with 400 when params are missing', function (done) {
  request(app)
    .post('/')
    .expect(401)
    .end(finish_test(done))
})
```
which is similar to the solution of @washimimizuku

**Comment by datatypevoid** [comment]
+1 @washimimizuku

**Comment by amandaducrou** [comment]
+1 @nesQuick

**Comment by acinader** [comment]
@nesQuick  you can simplify it a bit by like so:

```
.expect(401, finnish_test(done))
```

but that this is even necessary makes me sad and want to change to mocha :(

**Comment by djungowski** [comment]
I used @nesQuick's solution to create this reusable npm package: https://www.npmjs.com/package/jasmine-supertest
