### ISSUE TITLE
Adding jasmine reporters to boot file.

### ISSUE THREAD

**Issue by johnsonw** [jasmine/jasmine-npm#37]
The latest version of jasmine-npm does not support adding a reporter in a boot file (see https://github.com/jasmine/jasmine-npm/issues/32). This appears to be fixed in master; is there any way a new release can be cut to make the fix available?

**Comment by slackersoft** [comment]
We're working on getting a release together with some other improvements from core as well, but there are a few more things we want to finish up before we cut the next version.
