### ISSUE TITLE
Custom reporter?

### ISSUE THREAD

**Issue by olalonde** [jasmine/jasmine-npm#41]
HI. I try to looks around the docs but couldn't find a way to change the default reporter to something more verbose. Is there a sample project that uses jasmine-npm in this way?

**Comment by slackersoft** [comment]
The jasmine npm only ships with a basic summary formatter. Check out the discussion in #32 for some suggestions about how to supply a custom formatter.

**Comment by slackersoft** [comment]
Closing.
