### ISSUE TITLE
How to get list of tests run?

### ISSUE THREAD

**Issue by keitha-cakewalk** [jasmine/jasmine-npm#42]
Running jasmine-node has a verbose option to list all tests it ran.  However, that doesn't list pending tests.

I'd actually prefer to run the jasmine CLI which lists the pending tests, but I can't find a way to list the specs that were run, I only see 
....
which doesn't tell me what sorts of tests were run.

Is there a way to do this?  Thanks

**Comment by slackersoft** [comment]
The jasmine npm only ships with a basic summary formatter. Check out the discussion in #32 for some suggestions about how to supply a custom formatter.
