### ISSUE TITLE
2.3.0 seems to return wrong exit code

### ISSUE THREAD

**Issue by lukas-zech-software** [jasmine/jasmine-npm#43]
I use [gulp-jasmine](https://github.com/sindresorhus/gulp-jasmine) to run my unit-test.

Since the update 2.3.0 in jasmine, which is installed in gulp-jasmine due to caret version binding, the process simply ends after running the unit tests.

It doesn't matter wether all unit tests are green or none unit tests are executed at all. The process simply stops.

I did not have time to isolate the specific code part responsible for this behaviour so far, but as exit behaviour [was changed in the last update](https://github.com/jasmine/jasmine-npm/commit/97c67d5a0888b2694069dc56403e170203bad365) it seems likely to be connected to this issue.
I try to investigate further to provide more details.

I'll add the environments were I experienced the behaviour, as the commit mentioned above  seems to deal with platform related code.

OS: OS X 10.10.13
NodeJS: 0.10.38 & 0.12.2
gulp-jasmine: 2.0.1

If needed I'll provide further details

**Comment by amavisca** [comment]
I tried a few different things and couldn't find any problems. I made a simple project from `jasmine init` `jasmine examples` and added a gulpfile with gulp-jasmine (includes jasmine 2.3.0).

We did change some things around exiting recently, but that was to only use the node-exit module (for a Windows + node < v0.12.0 bug) when it was needed as opposed to always using it.

Can you provide more details?

**Comment by lukas-zech-software** [comment]
So after digging deeper in the code and comparing the difference between jasmine 2.3.0 and 2.2.1 and how its is called by gulp-jasmine 2.0.1 it seems that the error is not caused  by jasmine returning the wrong error code, but oddly by return at error code **at all**

gulp-jasmine, by default, adds a [jasmine-terminal-reporter](https://github.com/dashthis/jasmine-terminal-reporter) which implements  __jasmineDone__ as NOOP ( function() {} ) as default

Therefore the **exit** module was actually never called, with no exit code what so ever.

Due to the new check [__onCompleteCallbackAdded__](https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L146) the __exitCodeReporter__ will now always invoke the **exit** module effectively killing the running node process with exit code 0 or 1 according to the result of the tests

So if I understand the code correctly, it seems that the solution is to add an onComplete handler to the jasmine object to set __onCompleteCallbackAdded__ to true, which must be done gulp-jasmine.
I would therefore open an issue on gulp-jasmine for that.

Can you confirm this or did I overlook something?
If my assumption is correct, shouldn't this be considered a breaking change which should reflect in the version number?

Thanks in advance

**Comment by rdy** [comment]
Hey,

We also got bitten by this issue when upgrading to jasmine 2.3.0. I don't know if it is a good idea that jasmine exits the whole process since that breaks a lot of tool chains (gulp, grunt, etc). Jasmine would run to completion but tasks that would normally have run after jasmine would not run anymore because of this exit.

In any case, I think the exit is a breaking change, I'd prefer to see that in a major release of jasmine rather than this minor release upgrade since it breaks toolchains.

It probably isn't ideal to force all the tools like gulp-jasmine to add a new callback to prevent the exit from occurring. All jasmine tools using the npm module would have to be fixed in a similar fashion. Is there a better way to fix the original windows bug that doesn't involve exiting?

**Comment by amavisca** [comment]
Thanks for the input -
I see this has nothing to do with the Windows exit fixes.

We originally had a default onComplete of process.exit in the default reporter but we were running into a lot of issues with having it live there. Now we've moved the onComplete handling out of the reporter up to jasmine, but this is a breaking change for everyone that wasn't using the default reporter.

We could revert back to having our default reporter process.exit (which causes a lot of problems) or we could remove the default onComplete from lib/jasmine and have bin/jasmine pass it in (which leaves those using lib/jasmine in a bad spot if they expect the process.exit by default).

**Comment by jbblanchet** [comment]
Hi,

I do agree that it's much better to have an onComplete event than to do it in the reporter. We had this problem in gulp-jasmine and ended up creating a fake silent reporter just to be able to call the callback.

But I also agree with @rdy that for now you should revert back to the previous behavior so dependent packages (like gulp-jasmine) and custom reporters continue to work, and maybe change this behavior in the next major release, or add an option to use either solutions for now but keep the current behavior by default and deprecate it in the next major release.

If you could provide an ETA for a solution, it would be much appreciated, so we know if we must release a new version of gulp-jasmine or wait for your fix.

Thanks.

**Comment by amavisca** [comment]
@jbblanchet I agree and expect to have a solution for this tonight (sometime after 7pm PDT).

**Comment by amavisca** [comment]
Keeping this issue open until we've actually pushed to npm for this.

**Comment by amavisca** [comment]
I pushed 2.3.1 to npm which should resolve this. Would you mind closing this issue if things are working as you expect?

**Comment by jbblanchet** [comment]
Thanks for the quick fix. I've tested it with gulp-jasmine and it appears to work just fine. If you're opening an issue for a long term solution (like moving to a onComplete event and deprecating the jasmineDone reporter event), feel free to tag me and I'll update gulp-jasmine.
