### ISSUE TITLE
Question: vendor scripts

### ISSUE THREAD

**Issue by SergioMorchon** [jasmine/jasmine-npm#46]
How can I load vendor scripts before running tests?

**Comment by slackersoft** [comment]
Your `jasmine.json` file can contain a `helpers` key, which is an array of file globs (relative to your `specDir`) that jasmine will load before loading and running your specs.

We're still working on some of the documentation for this, but in general you are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

Thanks for using jasmine! Closing.
