### ISSUE TITLE
jasmine.json documentation

### ISSUE THREAD

**Issue by sabrehagen** [jasmine/jasmine-npm#49]
Can you please supply some documentation on the structure of the jasmine.json file?

**Comment by amavisca** [comment]
http://jasmine.github.io/2.3/node.html#section-Configuration

Thanks for using Jasmine!

**Comment by sabrehagen** [comment]
Thanks for the link! If you could put it in your readme others in my newbie position wouldn't run into the same issue :)

**Comment by Ruff9** [comment]
I can't find any info on how to deal with source files in the jasmine.json. Can you help me on this ? Thanks

**Comment by amavisca** [comment]
You don't need to specify your source files in the config - just require them in from your spec files.

**Comment by Ruff9** [comment]
Thanks, the sentence " to enumerate the source files and spec files you would like the Jasmine runner to include. " was misleading. I have an issue with Jquery, that jasmine apparently can't find, and I hoped it was a way to solve it.

**Comment by scirelli** [comment]
is there something like the "watch" and "autotest" flags for the jasmine.json file?

**Comment by slackersoft** [comment]
@scirelli Jasmine doesn't have any `watch` or `autotest` flags that can be set. Maybe you're using a different library?

**Comment by scirelli** [comment]
Yea, I was using jasmine-node or something before. Nm.

**Comment by e-cherrier** [comment]
hi, how to exclude the node_modules folder ?
thanks

**Comment by e-cherrier** [comment]
oops, I just missed the ! before the directory that was in the doc.
so we need to prefix the unexpected dir by an ! in the "spec_files"
see https://jasmine.github.io/setup/nodejs.html

**Comment by anjansagar** [comment]
Can someone help to set jasmine json-reporter?please

Thanks

**Comment by AcademyOfF** [comment]
I can't find a reference documentation anywhere for this file. unless, is the Configuration section of https://jasmine.github.io/setup/nodejs.html a complete reference?
