### ISSUE TITLE
add --watch option

### ISSUE THREAD

**Issue by geddski** [jasmine/jasmine-npm#5]
a watch option using [gaze](https://www.npmjs.org/package/gaze) or similar would be super helpful.

**Comment by slackersoft** [comment]
Because jasmine-npm uses `require` to load your spec file, which probably also use `require` to load the system under test, I think it makes the most sense for a `jasmine --watch` command to `fork` a child process that will get its own `require` cache so it will always run with the current code.

**Comment by Isaddo** [comment]
@danmartinez101 if you install `nodemon` and `jasmine` globally

    npm install -g nodemon
    npm install -g jasmine

you can just run `nodemon --exec jasmine` in command line.

**Comment by danmartinez101** [comment]
@Isaddo Yea, that is more concise for the most common scenario. I probably should have use that up above... Personally, I like to refrain from installing global cli packages because I often need to use different versions of jasmine, etc for different project concurrently. It may have changed since the last time I tried, but I found that a global install would override a local install so I had to go with the longer commands.

**Comment by sabrehagen** [comment]
so does anybody have a clean and working solution for this? it's really essential.

**Comment by slackersoft** [comment]
Given how easy it is to accomplish this without any changes to jasmine-npm itself, we would prefer to spend our limited development time working on other features. We'd be happy to review a pull request that implements it.

**Comment by jameswilddev** [comment]
I'd like to see this too.  Some of the other Jasmine test runners implement this (but are missing other features) and seem to get better performance when re-running tests.  (presumably some kind of caching going on)

**Comment by hendrauzia** [comment]
It can be tricky to be implemented if someone is using babel-node to run their jasmine node tests. I have to use the following code in order to run jasmine test files using babel-node automatically on any changes to test or code:

    ./node_modules/nodemon/bin/nodemon.js -w spec/lib -w lib ./node_modules/babel-cli/bin/babel-node.js ./node_modules/jasmine/bin/jasmine.js --random=true

The good thing is, it can be put as an npm script as follows:

    // package.json
    "scripts": {
      "watch": "./node_modules/nodemon/bin/nodemon.js -w spec/lib -w lib ./node_modules/babel-cli/bin/babel-node.js ./node_modules/jasmine/bin/jasmine.js --random=true"
    }

**Comment by Izhaki** [comment]
I'm going against the stream and would argue jasmine shouldn't support a watch function.

To begin with, I think only very light projects will need a watch on jasmine only. Many projects involve more than one watch.

Then, adding watch to jasmine means adding complexity and maintenance overhead (even if the implementation simply delegates the job to another module). 

The task of watching files is not a trivial one - this repository will start seeing issues related to watch not working on Windows, double triggering, no triggering and so forth that have nothing to do with jasmine.

Finally, and most importantly, recall the **separation of concerns** principle. Ideally jasmine should change for its prime purpose only - running tests.

Don't quite see the issue with this using `nodemon` or gulp or grunt or:

```json
  "scripts": {
    "watch:specs": "chokidar -p 'src/**/*.spec.ts' -c 'npm run test'",
    "test": "./jasmine.js"
  }
```

**Comment by slackersoft** [comment]
At this point, I think it makes more sense to leave the code to do the watching of your specs and production code to one of the _many_ external libraries that are built specifically for that. This allows more flexibility for people to pick the watcher library that works best for them, and to update or change it without having to wait for Jasmine to release a new version. It also won't (as @Izhaki [says](https://github.com/jasmine/jasmine-npm/issues/5#issuecomment-254955980)) cause the Jasmine team to have to deal with or troubleshoot any issues related to the watching not working correctly.

Thanks for all the input. Closing this. Thanks for using Jasmine!

**Comment by dkfiresky** [comment]
@slackersoft
> This allows more flexibility for people to pick the watcher library that works best for them

Why there is the following statement on the [Jasmine Docs](https://jasmine.github.io/):
> Comes out of the box with everything you need to test your code.

Re-running tests is also a purpose of most of the existing tasks runners

**Comment by champi-dev** [comment]
This works for me:
```json
{
    "test": "jasmine",
    "test:watch": "nodemon -e js --exec 'npm run test'"
}
```
