### ISSUE TITLE
onComplete never fires

### ISSUE THREAD

**Issue by CodeOtter** [jasmine/jasmine-npm#52]
Jasmine version is 2.3.2

```javascript
// testStarter.js
var Jasmine = require('jasmine');
var Sails = require('sails/lib/app');
var TestConfig = require('../config/env/test');
var jasmine = new Jasmine();
var app = new Sails();
jasmine.loadConfigFile('test/support/jasmine.json');
jasmine.configureDefaultReporter({
    showColors: true
});

jasmine.onComplete(function(passed) {
  console.log('passed');
  app.lower(function() {
    console.log('lowered');
  });
});

app.lift(TestConfig, function(err, sails) {
  console.log('lifted');
  jasmine.execute();
});
```

```javascript
// SomeSpec.js
  describe('Sample Test', function() {
    it('should do all the things', function() {
      expect(true).toEqual(true);
    });
  });
```

From the CLI:
```node spec/testStarter.js```

Output:
```
> project@1.0.0 test /var/www/project
> node spec/testStarter.js

lifted
Started
.
```

```
// test/support/jasmine.json
{
    "spec_dir": "spec",
    "spec_files": [
        "**/*[sS]pec.js"
    ],
    "helpers": [
        "helpers/**/*.js"
    ]
}
```

It just sits there indefinitely.

**Comment by CodeOtter** [comment]
If I have my ``spec_files`` not use glob and, instead, specify each directory, onComplete fires.  o___O

**Comment by amavisca** [comment]
@CodeOtter Were you able to solve this issue? What's the difference in spec files between you specifying the directories and the output of jasmine globbing them?

You can log the final call to load each file here: 
https://github.com/jasmine/jasmine-npm/blob/master/lib/jasmine.js#L62

**Comment by CodeOtter** [comment]
I bypassed this problem by not using double asterisks globbing.

**Comment by amavisca** [comment]
I'm not exactly sure what the problem was here under the hood - maybe some extra files were getting grabbed that affected your tests with the glob. 

I haven't seen other issues around this so I'm going to close the issue - definitely open this up if you run into problems again.

Thanks!
