### ISSUE TITLE
Running with harmony enabled

### ISSUE THREAD

**Issue by alexanderchr** [jasmine/jasmine-npm#54]
It's currently possible to run jasmine in harmony mode with `node --harmony node_modules/jasmine/bin/jasmine.js` but it would be convenient to be able to run `jasmine --harmony`. Is this a feature you'd like?

**Comment by slackersoft** [comment]
This seems like it would be a nice feature for people working with the new feature set. Ideally, I would prefer to see some way to pass generic unknown flags along to the node process in case there are any other types of things, or just a `--node-options` argument or something. I'm not sure what that would actually look like.

I'd be happy to review a pull request that did either of those things.

**Comment by lazarljubenovic** [comment]
Any updates on this?

**Comment by alexanderchr** [comment]
Don't think so. Most harmony features are enabled by default since node 6 anyways. If you need more (modules, async/await), use Babel. 



/Alexander

**Comment by slackersoft** [comment]
It sounds like this is less important now that these features are on by default in newer versions of node, so I'm going to close this. We would still be happy to review a pull request that allows the user to pass options through to node without having to execute `node` directly.

Thanks for using Jasmine!
