### ISSUE TITLE
How do you remote debug Jasmine tests?

### ISSUE THREAD

**Issue by galderz** [jasmine/jasmine-npm#57]
With `jasmine-node`, you can execute:

    node --debug-brk node_modules/jasmine-node/lib/jasmine-node/cli.js spec/codec_spec.js

Then, from the IDE I can open a remote Node.js debug session on port `5858`.

Is it possible to do something similar with `jasmine`/`jasmine-npm` ?

**Comment by slackersoft** [comment]
You are more likely to get quicker responses from the community for "How to use jasmine?" questions and a history of other solutions on the [jasmine-js group](https://groups.google.com/group/jasmine-js). We try to keep jasmine's github issues list focused on bugs and feature requests for jasmine itself.

You probably want to execute `bin/jasmine.js` to accomplish the same for jasmine-npm.

Thanks for using jasmine! Closing.
