### ISSUE TITLE
Minor documentation error regarding configureDefaultReporter()

### ISSUE THREAD

**Issue by cosmosb** [jasmine/jasmine-npm#59]
As per this: http://jasmine.github.io/2.3/node.html

> If you add a reporter through addReporter, the default ConsoleReporter will not be added.

But that isn't true. I just tried configuring default reporter and also added custom reporter. Both seem to work which is in fact very good and desired.

**Comment by amavisca** [comment]
I think the correct wording on this should be more like:

"If you have not added a reporter and have not configured the default reporter, a default reporter will be added."

The docs repo lives [here](https://github.com/jasmine/jasmine.github.io) if you'd like to send up a PR, if not I'll fix up the copy.

Thanks!

**Comment by cosmosb** [comment]
That is better. Won't send PR for this issue since it is minor. Thanks for fixing it and docs repo link.
