### ISSUE TITLE
Remove dependency on jasmine.json file when running tests 

### ISSUE THREAD

**Issue by indigo0086** [jasmine/jasmine-npm#61]
I want to be able to run individual tests with jasmine and node but the runner requires jasmine.json to be created.  Can this dependency be optional and favor cli arguments for specifying a path or regex to determine which tests to run.

**Comment by amavisca** [comment]
You can filter individual tests with the `jasmine --filter="some string"`or specify a file name with `jasmine path/to/spec/file.js`.

There are some docs here:
http://jasmine.github.io/edge/node.html#section-Running_tests

You can also use `fit` and `fdescribe` to focus within your code:
http://jasmine.github.io/edge/focused_specs.html

Feel free to close this if these solved your issue!

**Comment by indigo0086** [comment]
I think there is a misunderstanding.  The problem is that the command requires a variable set to point to a jasmine.json file which I feel for most cases is redundant.  I'd prefer a solution as simple as  ```jasmine path/to/spec/**/*.spec.js```  The whole needing to have the jasmine.json file I feel is pretty redundant and for most cases not needed.

**Comment by amavisca** [comment]
@indigo0086 
Yep, you're right. We started by adding these features in one by one and originally depended on having that json file around. As we've added more CLI options it seems like we're at the point where that file can be optional. I'd be happy to look at a PR that does that.

**Comment by jasonkarns** [comment]
Probably as a separate issue, but I would have much preferred to see a `jasmine` property in package.json that contained all the jasmine-specific config, rather than Yet Another Config File™

**Comment by slackersoft** [comment]
@jasonkarns That sounds reasonable as well. As @amavisca mentioned some of this grew a bit organically based on how we had configured some of the other Jasmine repositories. We would be happy to review a pull request that allows Jasmine to read its config from the including project's `package.json` file. For now it should leave the jasmine.json file parsing as a fallback if there is no jasmine config in package.json

**Comment by slackersoft** [comment]
Closed with #74
