### ISSUE TITLE
jasmine examples fails with npm@3

### ISSUE THREAD

**Issue by danielsiwiec** [jasmine/jasmine-npm#63]
As the transitive dependency structure for npm 3 is different than with npm 2, the cli ```jasmine examples``` command fails with:

```
Error: ENOENT: no such file or directory, scandir '.../node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/example/node_example/spec/helpers/jasmine_examples'
```

**Comment by SeanHayes** [comment]
This is still an issue for me in 2.4.1. When will the fix be released?

**Comment by slackersoft** [comment]
2.5.2 is out and should include the fix for this.
