### ISSUE TITLE
Cannot remove default report when using current environment

### ISSUE THREAD

**Issue by mauricioborges** [jasmine/jasmine-npm#66]
Hi there,

I was checking the issues #20 and #21, and I believed that the solution proposed in #21 would solve my problem. However, when I use jasmine.getEnv().addReport it does not work. I've created a helper with the following content:

```node
var SpecReporter = require('jasmine-spec-reporter');
jasmine.getEnv().addReporter(new SpecReporter());

```
And the default reporter is also added when running.

I've created an example into the specification: https://github.com/mauricioborges/jasmine-npm/commit/c5e466dd43bfdf357d5be42b3b5f095f947e5a99 but I'm not sure if I'm using the correct approach. As I'm using the double env method, it's feasible that it won't work.

Thanks for all your help!

**Comment by kamronbatman** [comment]
I get the same problem, with the exact same code.

**Comment by mauricioborges** [comment]
actually I've submitted 2 PRs related to it, #67 and https://github.com/jasmine/jasmine/pull/1009. Take a look if it could help you also. I've changed the approach for default report, using the default only when there's no reports provided.
