### ISSUE TITLE
Option spec_dir

### ISSUE THREAD

**Issue by dflynn15** [jasmine/jasmine-npm#69]
I was curious what the motivation for specifying the `spec_dir` option was. 
_Note: Most observations are based on a cursory look through the code base and not someone who has created it._

It appears to me as if the `spec_dir` is a convenient abstraction from adding `spec/` to the files/helpers/config. Could this not be an optional parameter for developers who have full paths and do not necessarily need the `spec_dir` option?

I realize that I am more than likely simplifying the necessity of the parameter, but it feels odd that you cannot run `jasmine` with only just the `spec_files`in Node.

**Comment by amavisca** [comment]
Yeah, I don't think spec_dir is very useful.
When we first started writing this module we were inspired by the ruby gem's configuration - but you're right in that the spec_dir use case doesn't make any sense for node. I'll take a look at the PR soon!
