### ISSUE TITLE
Configurable loaders

### ISSUE THREAD

**Issue by briandipalma** [jasmine/jasmine-npm#7]
I'd like to write my tests in ES6 as my source code is now ES6, currently as it stands I'd have to compile them into CJS to get them to run. It seems to me that jasmine-npm could support a configurable loader to remove the need to build the source.

```javascript
Jasmine.prototype.loadSpecs = function() {
this.specFiles.forEach(function(file) {
require(file);
});
};
```

If `loadSpecs` returned a `Promise` you could allow async loading of files via loaders. Maybe a configuration like,

```json
{
  "spec_dir": "spec",
  "spec_files": [
    "**/*[sS]pec.js"
  ],
  "helpers": [
    "helpers/**/*.js"
  ],
  "loader": "spec/es6-loader.js"
}
```

would allow people to load a file path and resolve a `Promise` once it's been executed so that Jasmine could go ahead and execute the tests.

I can give this a shot if you don't mind some extra dependencies in this project?

**Comment by amavisca** [comment]
We don't like the idea of pulling in a promise library when a promise standard doesn't exist in stable versions of node yet.

We'd be interested in supporting custom loaders but we'd like to be handed a synchronous function to be a replacement to `require`. This leaves resolving promises/dealing with async up to the consumer.

**Comment by briandipalma** [comment]
It appears as if 6to5 has support for testing there is no need for custom loader support.
