### ISSUE TITLE
Test suite overview

### ISSUE THREAD

**Issue by ath88** [jasmine/jasmine-npm#71]
It would be great to have an option for jasmine to merely print the full sentence BDD descriptions, while not actually running the tests.

I was thinking something like `jasmine --print-suites`, which could output something like;
```
> jasmine --print-suites
object
  constructor
    succeeds
    fails when missing vital parameter
  method
    returns 1 when this
    returns 2 when that
```
.. where `object`, `constructor` and `method` are `describe`s and the remaining are `it`s. Alternatively, it could print the full sentences, like this;

```
> jasmine --print-suites
object constructor succeeds
object constructor fails when missing vital parameter
object method returns 1 when this
object method returns 2 when that
```
I realise this might require more functionality in core jasmine, but I thought I'd suggest it here first.

**Comment by slackersoft** [comment]
You should be able to implement something like this by loading up a Jasmine environment (just using raw jasmine-core) and then inspecting the `topSuite` and its `children` (suites and specs).

This isn't something we're looking to put into Jasmine itself at this point, but we would be happy to point to a library that does this using the strategy I suggested.

Closing. Thanks for using Jasmine!
