### ISSUE TITLE
update glob dependancy

### ISSUE THREAD

**Issue by UziTech** [jasmine/jasmine-npm#78]
when installing jasmine a warning pops up

`npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

`minimatch` is a dependency of `glob` and updating the `glob` dependency will fix this

**Comment by amavisca** [comment]
I'll try to get a release out fixing a few things like this tonight.

**Comment by Harsha509** [comment]
Is there any ETA for next release ?

**Comment by amavisca** [comment]
No.

Waiting to get some clarity here first: https://github.com/jasmine/jasmine/issues/1144

Otherwise I'd have to cherry pick some commits into a release just for npm which is lame.

**Comment by RomanMetix** [comment]
Hey just ran into this exact problem, has there been any progress on a fix?

Thanks!
