### ISSUE TITLE
Command line argument to specify path to your jasmine.json (no environment variable required please)

### ISSUE THREAD

**Issue by mmc41** [jasmine/jasmine-npm#85]
I am using jasmine with npm and a complex typescript nodejs project that needs jasmine.json in a non-default place. Right now the jasmine executable will not let me supply the path to the 'jasmine.json' file but insist on a environment variable (an antipattern which I do not like because of pollution of the global environment etc). Hence, I would like the jasmine npm executable to take a -config argument where I can specify the relative path to the 'jasmine.json' file.

**Comment by amavisca** [comment]
You can pass it after but still using the env variable like syntax (which is kind of awkward but oh well).

http://jasmine.github.io/2.4/node.html#section-18

**Comment by mmc41** [comment]
@amavisca Don't understand. The linked pages does not state how to do this.

**Comment by amavisca** [comment]
Instead of `JASMINE_CONFIG_PATH=spec/config/jasmine.json jasmine`

You can do `jasmine JASMINE_CONFIG_PATH=spec/config/jasmine.json`

**Comment by mmc41** [comment]
Thanks. Pretty awkward. Why not a sensible command line argument ?

**Comment by slackersoft** [comment]
Allowing the config file to be specified by an environment variable allows things like travis build matrices to be easily configured to use different config files if necessary. It is also a legacy feature from the ruby gem that uses `rake` tasks that make it a bit harder to get other kinds of params from the command line.

That said, I would be happy to review a pull request that allows the config file path to alternatively be specified with a `--config`/`-c` option or something.
