### ISSUE TITLE
Separate jasmine instance combine specs

### ISSUE THREAD

**Issue by jbblanchet** [jasmine/jasmine-npm#86]
If you run the following code:

```javascript
const path = require('path')
const Jasmine = require('jasmine');
const Reporter = require('jasmine-terminal-reporter')

const jasmine1 = new Jasmine()
const jasmine2 = new Jasmine()

jasmine1.addReporter(new Reporter())
jasmine2.addReporter(new Reporter())

jasmine1.addSpecFile(path.join(__dirname, 'test1.spec.js'))
jasmine2.addSpecFile(path.join(__dirname, 'test2.spec.js'))

jasmine1.execute()
jasmine2.execute()
```

the 2 specs will run in the same instance of jasmine, and you'll get the following output:
```
0 specs, 0 failures
Finished in 0 seconds

..
2 specs, 0 failures
Finished in 0 seconds
```

I'd expect separate instances to keep track of their own specs. Is that assumption wrong?

**Comment by slackersoft** [comment]
Jasmine doesn't really expect that you've got more than one instance of it available at any given time. 

Currently when you boot up Jasmine in process, it adds all of the interface methods (`describe`, `it`, etc) to the global object and wraps them to add to the Jasmine `Env` that is currently booted. In your example, when the second `Jasmine` is constructed, it overwrites those global functions with new versions that put everything into the second instance.

If you really want to have two instances of Jasmine in the same process, you'll want to add everything to the first one before creating the second to get around this issue. But, I'm sure why you need to do that.

I don't think booting more than one Jasmine in the same process is something we're looking to support right now, but it might be good to not install on the global by default at some point.

Closing this. Thanks for using Jasmine!

**Comment by jbblanchet** [comment]
@slackersoft Thank you for your answer.

Like it's mentioned in the linked issue, the problem here is that someone is trying to have 2 separate tasks in gulp-jasmine. I'll find a solution inside of gulp-jasmine, but I think the fact that jasmine-npm is exposing a constructor (`var jasmine = new Jasmine()`) would imply by convention that each instance should be independent. Food for thought. :smiley:
