### ISSUE TITLE
v2.5.2 breaks tool chains

### ISSUE THREAD

**Issue by flore77** [jasmine/jasmine-npm#93]
In the 2.5.2 version like in the 2.5.0 and 2.3.0 versions, Jasmine will run to completion, but tasks that would normally have run after Jasmine finishes, would not run anymore, because Jasmine exists due to the `ExitCodeReporter/CompletionReporter` and effectively kills the process.

The issue was once solved through #43 in the v2.3.1.
Then it is was fixed in #89 in the v2.5.1 version.

But now in the v2.5.2 is back, because now the `CompletionReporter`, the ex `ExitCodeReporter`, is added in the [execute](https://github.com/jasmine/jasmine-npm/blob/43a219f832e424039089ec8f916faac3f2f27b4b/lib/jasmine.js#L178) function, so it cannot be cleared like the `ConsoleReporter`.

I don't if this is the desired behavior.

If it is not, I see 2 quick fixes:

Fix 1 - in the execute function
```js
// Apply the default exiting only if the default reporter is used, i.e ConsoleReporter.
if (this.reportersCount === 0) {
    this.addReporter(this.completionReporter);
}
```
OR

Fix 2 - in the constructor
```js
// Add the CompletionReporter at the same time with ConsoleReporter, so both can be cleared.
this.env.addReporter(this.completionReporter);
```

I thought only about this 2 sols, of which I think "Fix 1" would be better, because it permits the user to add a third party reporter and at the same time keep the default console reporting.

The above are quick fixes, but maybe it would be better to have an onComplete event, or something along this line, rather than do it in the reporter.

Currently this can be over passed with `jasmine.completionReporter.onComplete(function() {});`, which overwrites the actual exit function...

At least, if indeed this is the desired behavior, but I wouldn't see why, the [this.reportersCount](https://github.com/jasmine/jasmine-npm/blob/43a219f832e424039089ec8f916faac3f2f27b4b/lib/jasmine.js#L21) prop should be removed, because it is redundant now.

**Comment by slackersoft** [comment]
This packages provides an `onComplete` callback off of the base `Jasmine` object. If you pass a function into that, e.g:

```javascript
var Jasmine = require('jasmine');
var jasmine = new Jasmine();
jasmine.onComplete(function(success) {
  // do your thing
});
```

This will replace the default completion behavior that exits the process. Sorry for the confusion, this was the intent of the initial exit code reporter split out.

Closing this as this is the currently desired functionality. Please let us know if this solution doesn't work for you.

**Comment by flore77** [comment]
Thanks for the quick answer! I think it is fine also for my use case, but I was in a doubt that this is the desired functionality, because I saw it like a breaking change API for the 2.x version, since the `onComplete` callback is not available in all versions.

Anyway at leat the [this.reportersCount](https://github.com/jasmine/jasmine-npm/blob/43a219f832e424039089ec8f916faac3f2f27b4b/lib/jasmine.js#L21) prop should be removed, because it is redundant now.
