### ISSUE TITLE
Rethink version number strategy

### ISSUE THREAD

**Issue by jbblanchet** [jasmine/jasmine-npm#94]
Right now, breaking changes are introduced in patch versions. For example, 2.5.2 is changing the interface around adding reporters, and the default reporter needs to be cleared now.

I understand your intention is to keep the same version as the main jasmine repo, but respecting semver would go a long way in making the ecosystem more stable, and libraries built around jasmine easier to maintain.

**Comment by jbblanchet** [comment]
See: https://github.com/sindresorhus/gulp-jasmine/issues/86

**Comment by amavisca** [comment]
Thanks for filing this issue.

Breaking changes in patch versions are not intended. 

I see the issue regarding the reporter in this repo but haven't had and will not have access to a development machine for some time (a few weeks maybe) to investigate. 

There seems to be a lot of reporter code changes.

If you have ideas on restoring the breaking interface, please submit a PR.

**Comment by jbblanchet** [comment]
Thanks for taking the time to answer me.

The breaking change already happened and has been fixed in gulp-jasmine, so it's no biggie. But this is not the first time that a breaking change has been inserted in a minor revision. And for many people, this meant broken builds until we could fix and deploy a patch. That's what I'm trying to prevent in the future.

When I first started working on gulp-jasmine, I suggested keeping the version number locked in step with jasmine for simplicity. @sindresorhus rightfully argued that we shouldn't, because this meant that the wrapper (gulp-jasmine) couldn't evolve independently and still follow semver. I think this is exactly what's happening here. The wrapper's (jasmine-npm) version is locked to the library version (jasmine-core), so they can't evolve separately. So breaking changes to the reporter, or to the complete callback, or the options can't be made safely, unless there's a major revision to jasmine itself.

That's why I think you should reconsider your versioning strategy. Let the wrapper and the 'wrappee' evolve separately. This way, releasing a new version will mean thinking about the version number, and incrementing the right part so that the semver convention is respected.

**Comment by amavisca** [comment]
I've expressed a similar opinion a few comments down here: https://github.com/jasmine/jasmine-npm/issues/81

**Comment by jbblanchet** [comment]
You're right. I didn't think that issue was related to versioning, so I didn't look at it. I'll close this one. But I still strongly support such a change.
