### ISSUE TITLE
configureDefaultReporter() options are lost

### ISSUE THREAD

**Issue by tomv564** [jasmine/jasmine-npm#95]
In 2.5.x versions of jasmine-npm, calling `configureDefaultReporter` before calling `execute` appears to lose the provided options. 

For example: `configureDefaultReporter({showColors: false})` has no effect, the only way to turn colours off is by setting `jasmine.showingColors = false`.

I believe this behaviour appeared with the removal of the `this.reportersCount === 0` check in https://github.com/jasmine/jasmine-npm/commit/5989948cafa5479f7bde23ddced2b8a3604d003a#diff-c413964b3d28796db67dd5fe1f43851bR136. 

Perhaps the fix is to check `this.defaultReporterAdded` before calling `configureDefaultReporter` in `execute`?

**Comment by jasonwells** [comment]
We are seeing the same behavior in 2.5.2. When `{print: function(){}}` is passed, the prints of `.` for success and `F` for failures is still occurring.

**Comment by slackersoft** [comment]
@tomv564 I think you're correct about the solution. I think we missed this use case in the recent reporter refactoring. We'd be happy to review a pull request that gates the default configuration of the default reporter on whether or not it has already been configured.

Thanks for using Jasmine!
