### ISSUE TITLE
--stop-on-failure=true doesn't play well with async tests

### ISSUE THREAD

**Issue by maio** [jasmine/jasmine-npm#99]
Given test

    describe("--stop-on-failure=true + async test", function () {
        it("should work but doesn't", function (done) {
            setTimeout(function () {
                expect(10).toEqual(20);
                done();
            }, 0);
        });
    });

When I run `jasmine --stop-on-failure=true test.js`

I expect output:

    Failures:
    1) --stop-on-failure=true + async test should work but doesn't
      Message:
        Expected 10 to equal 20.

But I get:

    /node_modules/jasmine-core/lib/jasmine-core/jasmine.js:349
            throw new j$.errors.ExpectationFailed();
            ^
    Error
        at Object.getJasmineRequireObj.errors (/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2761:33)
    ...

**Comment by slackersoft** [comment]
You are correct, and this is something that needs to be fixed in Jasmine-Core (see jasmine/jasmine#529). This is on the top of my list for the next time I actually get time to write code for Jasmine.

I'm going to close this in favor of the issue in jasmine-core. Thanks for using Jasmine!
